//
//  QuestionStore.swift
//  BoysVersusGirlsGame
//
//  Created by Алексей on 27.01.2023.
//

import Foundation

class QuestionStore {
    
    public let questions: [Question] = [
        
        Question(sex: .female,
                 image: "plane",
                 title: "Зачем педали самолету?",
                 answer: [Answer(title: "Управлять хвостом", correct: true),
                          Answer(title: "Набирать скорость", correct: false),
                          Answer(title: "Заряжать аккумулятор", correct: false)]),
    Question(sex: .female,
                 image: "harlamov",
                 title: "Какой сценический псевдоним носит Гарик Харламов?",
                 answer: [Answer(title: "Бульдог", correct: true),
                          Answer(title: "Снежок", correct: false),
                          Answer(title: "Шарпей", correct: false)]),
     Question(sex: .female,
                 image: "perforator",
                 title: "Что делает перфоратор?",
                 answer: [Answer(title: "Сверлит", correct: false),
                          Answer(title: "Долбит", correct: false),
                          Answer(title: "Сверлит и долбит", correct: true)]),
    Question(sex: .female,
                 image: "bolt",
                 title: "Что изображено на картинке?",
                 answer: [Answer(title: "Винт", correct: false),
                          Answer(title: "Болт", correct: true),
                          Answer(title: "Шуруп", correct: false)]),
    Question(sex: .female,
                 image: "infiniti",
                 title: "Что за марка машины изображена на картинке?",
                 answer: [Answer(title: "Mazda", correct: false),
                          Answer(title: "Infiniti", correct: true),
                          Answer(title: "Maserati", correct: false)]),
    Question(sex: .female,
                 image: "carcandles",
                 title: "Что изображено на картинке?",
                 answer: [Answer(title: "Шурупы", correct: false),
                          Answer(title: "Втулки", correct: false),
                          Answer(title: "Свечи зажигания", correct: true)]),
     Question(sex: .female,
                 image: "worldcup",
                 title: "Страна, имеющая наибольшее количество титулов Чемпиона Мира?",
                 answer: [Answer(title: "Бразилия", correct: true),
                          Answer(title: "Англия", correct: false),
                          Answer(title: "Испания", correct: false)]),
    Question(sex: .female,
                 image: "transfer",
                 title: "Самый дорогой игрок в истории футбола (222 миллиона евро)?",
                 answer: [Answer(title: "Месси", correct: false),
                          Answer(title: "Неймар", correct: true),
                          Answer(title: "Роналду", correct: false)]),
    Question(sex: .female,
                 image: "football",
                 title: "Где зародился современный футбол?",
                 answer: [Answer(title: "Италия", correct: false),
                          Answer(title: "Бразилия", correct: false),
                          Answer(title: "Англия", correct: true)]),
    Question(sex: .female,
                 image: "firstcar",
                 title: "Первая конвейерная машина?",
                 answer: [Answer(title: "Renault", correct: false),
                          Answer(title: "Ferrari", correct: false),
                          Answer(title: "Ford", correct: true)]),
    Question(sex: .female,
                 image: "goalkeeper",
                 title: "Единственный вратарь, в истории футбола, получивший золотой мяч?",
                 answer: [Answer(title: "Лев Яшин", correct: true),
                          Answer(title: "Джанлуиджи Буффон", correct: false),
                          Answer(title: "Петер Шмейхель", correct: false)]),
        Question(sex: .female,
                 image: "gates",
                 title: "Какова высота футбольных ворот?",
                 answer: [Answer(title: "6 футов", correct: false),
                          Answer(title: "8 футов", correct: true),
                          Answer(title: "10 футов", correct: false)]),
        Question(sex: .female,
                 image: "computer",
                 title: "Как называется дефект, появляющийся неоднократно в компьютерной программе?",
                 answer: [Answer(title: "Баг", correct: true),
                          Answer(title: "Глюк", correct: false),
                          Answer(title: "Клин", correct: false)]),
        Question(sex: .male,
                 image: "stylist",
                 title: "Как называется мастер по созданию индивидуального стиля в одежде, причёске, макияже?",
                 answer: [Answer(title: "Визажист", correct: false),
                          Answer(title: "Муляжист", correct: false),
                          Answer(title: "Стилист", correct: true)]),
    Question(sex: .male,
                 image: "gortenziya",
                 title: "Какой цветок ихображен на картинке?",
                 answer: [Answer(title: "Астра", correct: false),
                          Answer(title: "Пион", correct: false),
                          Answer(title: "Гортензия", correct: true)]),
    Question(sex: .male,
                 image: "kerler",
                 title: "Что это такое?",
                 answer: [Answer(title: "Кёрлер", correct: true),
                          Answer(title: "Щипцы", correct: false),
                          Answer(title: "Мёрлер", correct: false)]),
    Question(sex: .male,
                 image: "dogfacedown",
                 title: "Как называется эта поза в йоге?",
                 answer: [Answer(title: "Собака мордой вниз", correct: true),
                          Answer(title: "Поза Согнутой свечи", correct: false),
                          Answer(title: "Поза Построения моста", correct: false)]),
        Question(sex: .male,
                 image: "sliponi",
                 title: "Что женщины предпочитают носить летом?",
                 answer: [Answer(title: "Тарпоны", correct: false),
                          Answer(title: "Слипоны", correct: true),
                          Answer(title: "Ботильоны", correct: false)]),
        Question(sex: .male,
                 image: "pilling",
                 title: "Как называется косметическая процедура по глубокой очистке кожи с помощью специальных кремов?",
                 answer: [Answer(title: "Стиллинг", correct: false),
                          Answer(title: "Пиллинг", correct: true),
                          Answer(title: "Диллинг", correct: false)])
    ]
}
